### ISSUE TITLE
Bash should pass all the tests

### ISSUE THREAD

**Issue by theoludwig** [cacharle/minishell_test#21]
Hey! :wave: @cacharle 

Great project to test if a shell follows specifications. :+1: 
For fun, I decided to test the real executable `bash` with this tool but somehow there are test failures, is `bash` not supposed to pass all the tests at least (as probably `bash` would do a lot more than what a Minishell project is supposed to do)? To be precise there are 621 PASS and 364 FAIL.

```sh
$ bash --version
GNU bash, version 5.1.8(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

## Steps to reproduce

```sh
mkdir Minishell ; cd Minishell
cp /bin/bash minishell
touch minishell_test.cfg
```

The content of `minishell_test.cfg` is the default from the documentation: https://minishell-test.readthedocs.io/en/latest/config.html, with exception that `make = false`.

```sh
$ cat minishell_test.cfg
[minishell_test]
bonus = false
exec_name = minishell
make = false
make_args = MINISHELL_TEST_FLAGS=-DMINISHELL_TEST
pager = false
pager_prog = less
log_path = minishell_test.log
check_error_messages = true
end_command_with_linefeed = true

[shell]
available_commands =
    rmdir
    env
    cat
    touch
    ls
    grep
    sh
    head
path_variable = {shell_available_commands_dir}

[shell:reference]
path = /bin/bash
args =

[timeout]
test = 0.5
leaks = 10
```

Then execute `minishell_test`.

Some explanation of how this project work, and what specification it tests actually would be helpful, thanks! :smile:

**EDIT:** Most of the tests failed because of the wrong path, using `exec name = /fullpath/minshell` instead of only `minishell` result in 926 PASS and 59 FAIL, so this is a lot better, but there are still 59 tests failures and I guess that shouldn't be the case.
First failing test from `minishell_test.log`:
```txt
|> WITH >\n
|---------------------------------------EXPECTED--------------------------------
/home/divlo/Downloads/Minishell/minishell: syntax error near unexpected token `newline'$
|---------------------------------------ACTUAL----------------------------------
/home/divlo/Downloads/Minishell/minishell: -c: syntax error near unexpected token `newline'$
/home/divlo/Downloads/Minishell/minishell: -c: `>'$
================================================================================
```

**Comment by cacharle** [comment]
If I remember correctly, all those errors should be about shell error messages.

Since the /bin/bash always as a `-c` and a second line (which is useless in our case) I remove them from the reference shell, not *minishell*.

When you launch bash in interactive mode instead of with the `-c` option. The error message I modify should look like this.

Here is the hook where I do the modification: https://github.com/cacharle/minishell_test/blob/master/minishell_test/hooks.py#L26

You can see there is a bunch of hooks to modify the output when it makes sense (e.g difference between Mac and Linux).

I don't really understand the full path for the `exec_name` option.

Hopes this clarify things.

Tell me if you find any error messages that are not due to hooks, otherwise I think this issue can be closed.

**Comment by theoludwig** [comment]
> and a second line (which is useless in our case)

Do you think I can try to open a PR to add an option in `minishell_test.cfg` to not remove this second line from the reference shell?

> which is useless in our case

Could you elaborate a bit more, about what is this second line and why it is useless, I don't really understand?

> I don't really understand the full path for the exec_name option.

Instead to set `exec_name = minishell`, I needed to do `exec_name = /home/divlo/Downloads/Minishell/minishell`, being the absolute path of the `minishell` executable.

**Comment by cacharle** [comment]
The second line in the error messages (`home/divlo/Downloads/Minishell/minishell: -c: '>'$`) only appears when you do `bash -c 'something'`, **not** when you run bash in the _normal way_ (what a called interactive mode earlier).

so:

```bash
$ bash
$ something (
error: foo bar
```

```bash
$ bash -c 'something ('
error: -c: foo bar
error: -c: xyz
```

So the second line **shouldn't** be in the error message of your minishell (same thing for the `-c` in the first line.

Some people have different error messages than the one of bash and I have an option in the configuration to discard the output of the tests which contains an error message.

You can make a PR if you want, make sure the current behavior stays the same by default. (altho I really don't see why anyone would want to keep the second line in the expected output)

Maybe the subject has changed and `-c` is asked now?

**Comment by cacharle** [comment]
I understood what you did with the executable just not **why** you had to do it.

Didn't work on this project for a while.

**Comment by theoludwig** [comment]
Okay right, thanks for the explanation, it makes sense! :smile:

I can close this issue now. :+1:
